package mainframe;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.xml.transform.Templates;

import frameActionPerformed.Mainframe_Renew;

import sql.getData;
import sql.putIn_Sql;

public class Addinfo_frame extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5643834889478009729L;
	private DefaultListModel<String> listModel1;
	DefaultMutableTreeNode top = new DefaultMutableTreeNode("Person");
    DefaultMutableTreeNode node1 = new DefaultMutableTreeNode("贴吧好友");
    DefaultMutableTreeNode node2 = new DefaultMutableTreeNode("微博好友");
    DefaultMutableTreeNode node3 = new DefaultMutableTreeNode("人人好友");
    DefaultTreeModel treeModel = new DefaultTreeModel(top);
    public static int updataflag[]=new int[4];
	String name=null;
    public Addinfo_frame() {
        initComponents();
        showlist();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addtieba = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addweibo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addrenren = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Allinfo_list = new javax.swing.JList();
        add_button = new javax.swing.JButton();
        view_button = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        
        top.add(node1);
        top.add(node2);
        top.add(node3);
        Relation_tree = new javax.swing.JTree(treeModel);
        setResizable(false);

        jLabel1.setText("姓名：");

        addname.setText("");

        jLabel2.setText("贴吧ID:");

        addtieba.setText("");

        jLabel3.setText("微博网址：");

        addweibo.setText("");

        jLabel4.setText("人人网址：");

        addrenren.setText("");

        Allinfo_list.setModel(new javax.swing.AbstractListModel() {
            /**
			 * 
			 */
			private static final long serialVersionUID = -1578493061637392387L;
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(Allinfo_list);

        add_button.setText("添    加");
        add_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_buttonMouseClicked(evt);
            }
        });

        view_button.setText("查    看");
        view_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                view_buttonMouseClicked(evt);
            }
        });

        jScrollPane3.setViewportView(Relation_tree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(add_button)
                        .addGap(110, 110, 110)
                        .addComponent(view_button))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addrenren, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addweibo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addname, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addtieba, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(addname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(addtieba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(addweibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(addrenren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add_button)
                            .addComponent(view_button))))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>                        

  
    private void add_buttonMouseClicked(java.awt.event.MouseEvent evt) { 
    	java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	 String Temp[]=new String[4];
                 Temp[0]=addname.getText();
                 Temp[1]=addtieba.getText();
                 Temp[2]=addweibo.getText();
                 Temp[3]=addrenren.getText();
                 for(int i=0;i<4;i++){
                	 if(Temp[i].equals("")){
                		 Temp[i]=null;
                		 updataflag[i]=0;
                	 }	
                	 else 
						updataflag[i]=1;
                 }
                 putIn_Sql.PutIn_Sql(Temp,5,"PersonInfo");     //此处要判断添加是否成功
                 if(putIn_Sql.hasperson==0){
                	 putIn_Sql.PutIn_Sql(Temp,6,"Person_State");   //添加状态
                 }
                 Mainframe.hasData=1;
                 JOptionPane.showMessageDialog(null, "添加信息成功","提示", JOptionPane.INFORMATION_MESSAGE); 
                 showlist();
                 Mainframe_Renew.newshow();     //每次添加完收藏人信息就更新一次主界面
            }
        });
    }                                       

    private void view_buttonMouseClicked(java.awt.event.MouseEvent evt) {    
    	java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	showlist();
            	top = new DefaultMutableTreeNode(name);
            	top.add(node1);
                top.add(node2);
                top.add(node3);
                treeModel = new DefaultTreeModel(top);
                Relation_tree = new javax.swing.JTree(treeModel);
                jScrollPane3.setViewportView(Relation_tree);
            }
    	  });
    } 
    
    public void showlist(){
    	if(Mainframe.hasData==1){
    		String uid[]=getData.GetPerson_name();
            listModel1 = new DefaultListModel<String>();  //人人使用
            for(int i=0;uid[i]!=null;i++)
    	            listModel1.addElement(uid[i]);
            Allinfo_list = new JList<String>(listModel1);
            Allinfo_list.addListSelectionListener(new ListSelectionListener() {
                public void valueChanged(ListSelectionEvent e) {
             	   name=(String) Allinfo_list.getSelectedValue();
             	 //  System.out.print(name);
                }
            });
            jScrollPane1.setViewportView(Allinfo_list);
    	}
    }

  

    // Variables declaration - do not modify                     
    @SuppressWarnings("rawtypes")
	private javax.swing.JList Allinfo_list;
    private javax.swing.JTree Relation_tree;
    private javax.swing.JButton add_button;
    private javax.swing.JTextField addname;
    private javax.swing.JTextField addrenren;
    private javax.swing.JTextField addtieba;
    private javax.swing.JTextField addweibo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton view_button;
    // End of variables declaration                   
}

