package mainframe;

import java.io.IOException;
import java.sql.Connection;
import java.util.jar.Attributes.Name;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import org.json.JSONException;

import Auto_analyse.newMessage_analyse;

import com.mashape.unirest.http.exceptions.UnirestException;

import sql.connect_sql;
import sql.getData;
import sql.hasTable;
import sql.table_Show;
import emotion_analysis.SentimentApiExample;
import filetest.deletefile;
import filetest.format;
import frameActionPerformed.Get_Listname;

public class Showframe extends javax.swing.JFrame {

    /**
	 * 
	 */
	public static int flag=4;      //记录选择分析的行数,默认分析全部
	private static final long serialVersionUID = 6174966022668909979L;
	/**
     * Creates new form NewJFrame1
     */
    public Showframe() {
        initComponents();
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	
    	setResizable(false);
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        select_item = new javax.swing.JComboBox();
        analyse = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        select_item.setModel(new javax.swing.DefaultComboBoxModel(new String[] {" ", "分析第一条", "分析前三条", "分析前五条", "分析所有" }));
        select_item.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selectItemStateChanged(evt);
            }
        });
        
        analyse.setText("开  始  分  析");
        analyse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                analyseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(select_item, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(analyse)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(select_item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(analyse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        
  
    
    public void showTable(){
    	    String name=null;
    	    name=Get_Listname.getListname();          //获取list列表指向对象的name
    	    if(name==null)
    	    	JOptionPane.showMessageDialog(null,"不能为空","提示",JOptionPane.ERROR_MESSAGE);
    	    else if(Mainframe.listflag==4){
    	    	setTitle(Warning_frame.T_name);
    	        DefaultTableModel myTable=table_Show.Show(Warning_frame.T_name);  /*连接数据库，将制定信息放入table*/
 			    jTable1=new JTable(myTable);
  		        jScrollPane1.setViewportView(jTable1);
    	    }
    	    else{
    	    	setTitle(name);
			    DefaultTableModel myTable=table_Show.Show(name);  /*连接数据库，将制定信息放入table*/
			    jTable1=new JTable(myTable);
 		        jScrollPane1.setViewportView(jTable1);
    	    }
    }
    
    private void analyseMouseClicked(java.awt.event.MouseEvent evt) {                                     
    	java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
           	 String name=null;
           	 name=Get_Listname.getListname();        //获取list列表指向对象的name
           	 if(name==null)
           		 JOptionPane.showMessageDialog(null,"不能为空","提示",JOptionPane.ERROR_MESSAGE);
           	 else{
           
           	 getData.Getsql_data(name);                                   /*获取name在数据库中对应表的数据*/
           	 SentimentApiExample sentimentAnalyse=new SentimentApiExample();    /*创建分析对象*/
           	 try {
           		 float score=0;
				try {
					score = sentimentAnalyse.analyse(name); 
					System.out.println(sentimentAnalyse.analyse(name));
				} catch (JSONException e) {
					e.printStackTrace();
				} catch (UnirestException e) {
					e.printStackTrace();
				}
       			 JOptionPane.showMessageDialog(null,"最终得分："+score,"分析窗口",JOptionPane.INFORMATION_MESSAGE);
       			 deletefile.Delete(name);     //删除文件
       			 
       		 } catch (IOException e) {
       			e.printStackTrace();
       		 }
           	 }
            }
        });
    } 
    
    private void selectItemStateChanged(java.awt.event.ItemEvent evt) {                                        
    	if(select_item.getSelectedIndex()==1)
    		flag=1;
    	else if(select_item.getSelectedIndex()==2)
    		flag=2;
    	else if(select_item.getSelectedIndex()==3)
    		flag=3;
    	else if(select_item.getSelectedIndex()==4)
    		flag=4;
    } 
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton analyse;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    @SuppressWarnings("rawtypes")
	private javax.swing.JComboBox select_item;
    // End of variables declaration                   
}