package mainframe;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.print.Printable;
import java.sql.Connection;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import sql.connect_sql;
import sql.hasTable;
import sql.table_Show;

import frameActionPerformed.Get_Listname;

import Auto_analyse.Timerclass;

public class Warning_frame extends javax.swing.JFrame {
	
	String Name[]=new String[3];
	static String T_name=null;

	public static DefaultListModel<String> warninglistModel;
    public Warning_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	setResizable(false);
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        warningList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("以下人员的情感值出现异常");
        
        warninglistModel = new DefaultListModel<String>();  
        for(int i=0;Timerclass.warning_name[i]!=null;i++){
        	warninglistModel.addElement(Timerclass.warning_name[i]);
        	Timerclass.warning_name[i]=null;
        }
        warningList = new JList<String>(warninglistModel);
        MouseListener mouseListener = new MouseAdapter() {
            public void mouseClicked(MouseEvent mouseEvent) {
              if (mouseEvent.getClickCount() == 2) {
            	  Mainframe.listflag=4;
            	  String name=null;
            	  name=Get_Listname.getListname();
      	    	  Name[0]=name+"的贴吧";
      	    	  Name[1]=name+"的微博";
      	          Name[2]=name+"的人人网";
      	    	  for(int i=0;i<3;i++){
      	    		 // System.out.print(Name[i]);
      	    		 Connection dbConn=connect_sql.Connect();
      	    		 int Has=0;
      	    		 try {
  						Has=hasTable.hastable(dbConn,Name[i]);
  					 } catch (Exception e) {
  						e.printStackTrace();
  					 }
      	    		 if(Has==1){
      	    			 T_name=Name[i];
      	    			 new Showframe().setVisible(true);        //双击显示
      	    		 }
      	    	  }
              }
            }
          };
        warningList.addMouseListener(mouseListener);
        jScrollPane1.setViewportView(warningList);

        jLabel2.setText("请 留 意");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel2)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JList warningList;
    // End of variables declaration                   
}
